# Generated by Django 5.2.5 on 2025-12-15 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address1', models.TextField(blank=True, max_length=50, null=True)),
                ('address2', models.TextField(blank=True, max_length=50, null=True)),
                ('landmark', models.TextField(blank=True, max_length=50, null=True)),
                ('city', models.TextField(blank=True, max_length=50, null=True)),
                ('state', models.TextField(blank=True, max_length=50, null=True)),
                ('pin_code', models.TextField(blank=True, max_length=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('cont_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('alt_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('is_gst_registered', models.BooleanField(default=False)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.accounts')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.address')),
            ],
            options={
                'db_table': 'contacts',
                'constraints': [models.UniqueConstraint(fields=('phone',), name='unique_contact_number')],
            },
        ),
    ]
