# Generated by Django 5.2.5 on 2025-12-17 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='jobslug',
        ),
    ]
