# Generated by Django 5.2.5 on 2025-12-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_jobslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_slug',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
